version: 2
jobs:
  build_py3:
    docker:
      - image: pshriwise/pshriwise:ubuntu_17.04_pymoab_pyne

    working_directory: ~/repo

    steps:
      - checkout

      # Build!
      - run:
          name: Building PyNE
          command: |
            pwd
            python3 setup.py install --user

      # Test!
      - run:
          name: Running PyNE Tests
          no_output_timeout: "20m"
          command: |
            cd ~/repo/tests
            ./travis-run-tests.sh python3
  
  build_py3_pymoab:
    docker:
      - image: bam241/ubuntu_16.04_py3_pymoab_pyne:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Build w/ PyMOAB
      - run:
          name: Building PyNE
          command: |
            pwd
            python setup.py install --user \
                --moab $HOME/opt/moab --dagmc $HOME/opt/dagmc --clean

      # Test w/ PyMOAB
      - run:
          name: Running PyNE Tests
          no_output_timeout: "20m"
          command: |
            cd ~/repo/tests
            ./travis-run-tests.sh python2

  build_py2:
    docker:
      - image: pshriwise/ubuntu_16.04_pymoab_pyne:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Build (no PyMOAB)
      - run:
          name: Building PyNE w/o PyMOAB
          command: |
            pwd
            python setup.py install --user --clean

      # Test (no PyMOAB)
      - run:
          name: Running PyNE Tests w/o PyMOAB
          no_output_timeout: "20m"
          command: |
            cd ~/repo/tests
            ./travis-run-tests.sh python2

  build_py2_pymoab:
    docker:
      - image: pshriwise/ubuntu_16.04_pymoab_pyne:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Build w/ PyMOAB
      - run:
          name: Building PyNE
          command: |
            pwd
            python setup.py install --user \
                --moab $HOME/opt/moab --dagmc $HOME/opt/dagmc --clean

      # Test w/ PyMOAB
      - run:
          name: Running PyNE Tests
          no_output_timeout: "20m"
          command: |
            cd ~/repo/tests
            ./travis-run-tests.sh python2

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_py2
      - build_py2_pymoab
      - build_py3
      - build_py3_pymoab
